CUDA_VISIBLE_DEVICES=1 python main.py --max_epochs=8  --num_workers=16 \
    --model_name_or_path facebook/bart-base \
    --accumulate_grad_batches 1 \
    --batch_size 16 \
    --data_dir dataset/semeval \
    --check_val_every_n_epoch 1 \
    --data_class BartREDataset \
    --max_seq_length 256 \
    --model_class BartRE \
    --litmodel_class BartRELitModel \
    --task_name wiki80 \
    --lr 1e-5
